defaults: &defaults
  app_name: ShopQi App Example
  author:
    email: mahb45@gmail.com
  oauth:
    client_id: dffd069fa92096022628a1f7eb174bc85d90278b8c90ec7ebadfbd94924bd2b8
    secret: e1805141c81c496e4779371f41263c9f74ac2ffd3728302296b8af10b64d9c9b
    scope: 'read_products read_orders'
    callback_path: '/callback'
  domain:
    record: 粤ICP备11089804号
  shopqi_domain:
    protocol: 'http://'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  oauth:
    client_id: dffd069fa92096022628a1f7eb174bc85d90278b8c90ec7ebadfbd94924bd2b8
    client_secret: e1805141c81c496e4779371f41263c9f74ac2ffd3728302296b8af10b64d9c9b
    scope: 'read_products read_orders'
    callback_path: '/callback'
  domain:
    record: 粤ICP备11089804号
  shopqi_domain:
    protocol: 'https://'
